apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.artifact_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    jenkins.io/github-folder: 'taly-deploy'
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
